name: Tests

on:
  push:
  pull_request:

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Dependencies
        uses: pnpm/action-setup@v2.2.1
        with:
          run_install: true
          version: 6.32.6

      - name: Run Unit Tests
        run: pnpm run test:unit
