name: PR Management

on:
  pull_request:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-20.04

    timeout-minutes: 30

    steps:
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pr-labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  assign:
    runs-on: ubuntu-20.04

    timeout-minutes: 30

    steps:
    - name: Assign PR using REST API
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/assignees \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "assignees": ["${{ github.event.pull_request.user.login }}"]
          }'
